#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _JARVIS_ROOT="$(abs_dirname "$libexec_path")"
export _JARVIS_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/jarvis/config.json"
export _JARVIS_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/jarvis"
export PATH="${libexec_path}:$PATH"

mkdir -p $(dirname ${_JARVIS_CONFIG}) $_JARVIS_DATA

. $_JARVIS_ROOT/share/jarvis/util.sh

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec jarvis-help
  ;;
* )
  command_path="$(command -v "jarvis-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "jarvis: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
